all = {
    "a": {
        "attributes": ["href", "target", "download", "rel", "hreflang", "type"],
        "self_closing": False,
    },
    "abbr": {"attributes": ["title"], "self_closing": False},
    "address": {"attributes": [], "self_closing": False},
    "area": {
        "attributes": ["alt", "coords", "shape", "href", "target", "download", "rel"],
        "self_closing": True,
    },
    "article": {"attributes": [], "self_closing": False},
    "aside": {"attributes": [], "self_closing": False},
    "audio": {
        "attributes": ["src", "controls", "autoplay", "loop", "muted", "preload"],
        "self_closing": False,
    },
    "b": {"attributes": [], "self_closing": False},
    "base": {"attributes": ["href", "target"], "self_closing": True},
    "bdi": {"attributes": [], "self_closing": False},
    "bdo": {"attributes": ["dir"], "self_closing": False},
    "blockquote": {"attributes": ["cite"], "self_closing": False},
    "body": {"attributes": [], "self_closing": False},
    "br": {"attributes": [], "self_closing": True},
    "button": {
        "attributes": [
            "type",
            "name",
            "value",
            "disabled",
            "autofocus",
            "form",
            "formaction",
        ],
        "self_closing": False,
    },
    "canvas": {"attributes": ["width", "height"], "self_closing": False},
    "caption": {"attributes": [], "self_closing": False},
    "center": {"attributes": [], "self_closing": False},
    "cite": {"attributes": [], "self_closing": False},
    "code": {"attributes": [], "self_closing": False},
    "col": {"attributes": ["span"], "self_closing": True},
    "colgroup": {"attributes": ["span"], "self_closing": False},
    "data": {"attributes": ["value"], "self_closing": False},
    "datalist": {"attributes": [], "self_closing": False},
    "dd": {"attributes": [], "self_closing": False},
    "del": {"attributes": ["cite", "datetime"], "self_closing": False},
    "details": {"attributes": ["open"], "self_closing": False},
    "dfn": {"attributes": [], "self_closing": False},
    "dialog": {"attributes": ["open"], "self_closing": False},
    "div": {"attributes": [], "self_closing": False},
    "dl": {"attributes": [], "self_closing": False},
    "dt": {"attributes": [], "self_closing": False},
    "em": {"attributes": [], "self_closing": False},
    "embed": {"attributes": ["src", "type", "width", "height"], "self_closing": True},
    "fieldset": {"attributes": ["disabled", "form", "name"], "self_closing": False},
    "figcaption": {"attributes": [], "self_closing": False},
    "figure": {"attributes": [], "self_closing": False},
    "footer": {"attributes": [], "self_closing": False},
    "form": {
        "attributes": [
            "action",
            "method",
            "enctype",
            "autocomplete",
            "target",
            "novalidate",
        ],
        "self_closing": False,
    },
    "h1": {"attributes": [], "self_closing": False},
    "h2": {"attributes": [], "self_closing": False},
    "h3": {"attributes": [], "self_closing": False},
    "h4": {"attributes": [], "self_closing": False},
    "h5": {"attributes": [], "self_closing": False},
    "h6": {"attributes": [], "self_closing": False},
    "head": {"attributes": [], "self_closing": False},
    "header": {"attributes": [], "self_closing": False},
    "hgroup": {"attributes": [], "self_closing": False},
    "hr": {"attributes": [], "self_closing": True},
    "html": {"attributes": [], "self_closing": False},
    "i": {"attributes": [], "self_closing": False},
    "iframe": {
        "attributes": ["src", "width", "height", "name", "sandbox"],
        "self_closing": False,
    },
    "img": {
        "attributes": ["src", "alt", "width", "height", "usemap", "ismap"],
        "self_closing": True,
    },
    "input": {
        "attributes": [
            "type",
            "name",
            "value",
            "placeholder",
            "required",
            "disabled",
            "readonly",
            "size",
            "maxlength",
            "autocomplete",
            "autofocus",
            "checked",
            "multiple",
            "min",
            "max",
            "step",
            "form",
            "formaction",
            "formenctype",
            "formmethod",
            "formnovalidate",
            "formtarget",
            "list",
            "pattern",
        ],
        "self_closing": True,
    },
    "ins": {"attributes": ["cite", "datetime"], "self_closing": False},
    "kbd": {"attributes": [], "self_closing": False},
    "label": {"attributes": ["for", "form"], "self_closing": False},
    "legend": {"attributes": [], "self_closing": False},
    "li": {"attributes": ["value"], "self_closing": False},
    "link": {
        "attributes": ["href", "rel", "type", "media", "hreflang", "sizes"],
        "self_closing": True,
    },
    "main": {"attributes": [], "self_closing": False},
    "map": {"attributes": ["name"], "self_closing": False},
    "mark": {"attributes": [], "self_closing": False},
    "meta": {
        "attributes": ["name", "http-equiv", "content", "charset"],
        "self_closing": True,
    },
    "meter": {
        "attributes": ["value", "min", "max", "low", "high", "optimum"],
        "self_closing": False,
    },
    "nav": {"attributes": [], "self_closing": False},
    "noscript": {"attributes": [], "self_closing": False},
    "object": {
        "attributes": ["data", "type", "width", "height", "name", "usemap", "form"],
        "self_closing": False,
    },
    "ol": {"attributes": ["reversed", "start", "type"], "self_closing": False},
    "optgroup": {"attributes": ["label", "disabled"], "self_closing": False},
    "option": {
        "attributes": ["value", "label", "selected", "disabled"],
        "self_closing": False,
    },
    "output": {"attributes": ["for", "form", "name"], "self_closing": False},
    "p": {"attributes": [], "self_closing": False},
    "param": {"attributes": ["name", "value"], "self_closing": True},
    "picture": {"attributes": [], "self_closing": False},
    "pre": {"attributes": [], "self_closing": False},
    "progress": {"attributes": ["value", "max"], "self_closing": False},
    "q": {"attributes": ["cite"], "self_closing": False},
    "rp": {"attributes": [], "self_closing": False},
    "rt": {"attributes": [], "self_closing": False},
    "ruby": {"attributes": [], "self_closing": False},
    "s": {"attributes": [], "self_closing": False},
    "samp": {"attributes": [], "self_closing": False},
    "script": {
        "attributes": [
            "src",
            "type",
            "async",
            "defer",
            "crossorigin",
            "integrity",
            "nomodule",
            "referrerpolicy",
        ],
        "self_closing": False,
    },
    "section": {"attributes": [], "self_closing": False},
    "select": {
        "attributes": ["name", "disabled", "form", "multiple", "required", "size"],
        "self_closing": False,
    },
    "small": {"attributes": [], "self_closing": False},
    "source": {
        "attributes": ["src", "type", "srcset", "sizes", "media"],
        "self_closing": True,
    },
    "span": {"attributes": [], "self_closing": False},
    "strong": {"attributes": [], "self_closing": False},
    "style": {"attributes": ["media", "type", "scoped"], "self_closing": False},
    "sub": {"attributes": [], "self_closing": False},
    "summary": {"attributes": [], "self_closing": False},
    "sup": {"attributes": [], "self_closing": False},
    "svg": {
        "attributes": ["width", "height", "viewBox", "xmlns", "fill", "stroke"],
        "self_closing": False,
    },
    "table": {"attributes": [], "self_closing": False},
    "tbody": {"attributes": [], "self_closing": False},
    "td": {"attributes": ["colspan", "rowspan", "headers"], "self_closing": False},
    "template": {"attributes": [], "self_closing": False},
    "textarea": {
        "attributes": [
            "name",
            "rows",
            "cols",
            "disabled",
            "readonly",
            "placeholder",
            "autofocus",
            "form",
            "maxlength",
            "minlength",
            "required",
            "wrap",
        ],
        "self_closing": False,
    },
    "tfoot": {"attributes": [], "self_closing": False},
    "th": {
        "attributes": ["colspan", "rowspan", "headers", "scope", "abbr"],
        "self_closing": False,
    },
    "thead": {"attributes": [], "self_closing": False},
    "time": {"attributes": ["datetime"], "self_closing": False},
    "title": {"attributes": [], "self_closing": False},
    "tr": {"attributes": [], "self_closing": False},
    "track": {
        "attributes": ["default", "kind", "label", "src", "srclang"],
        "self_closing": True,
    },
    "u": {"attributes": [], "self_closing": False},
    "ul": {"attributes": [], "self_closing": False},
    "var": {"attributes": [], "self_closing": False},
    "video": {
        "attributes": [
            "src",
            "controls",
            "autoplay",
            "loop",
            "muted",
            "poster",
            "preload",
            "width",
            "height",
            "playsinline",
        ],
        "self_closing": False,
    },
    "wbr": {"attributes": [], "self_closing": True},
}
# TODO: decide if constant lookup time is better (prob not lol)
properties = [
    "accent-color",
    "align-content",
    "align-items",
    "align-self",
    "all",
    "animation",
    "animation-delay",
    "animation-direction",
    "animation-duration",
    "animation-fill-mode",
    "animation-iteration-count",
    "animation-name",
    "animation-play-state",
    "animation-timing-function",
    "aspect-ratio",
    "backdrop-filter",
    "backface-visibility",
    "background",
    "background-attachment",
    "background-blend-mode",
    "background-clip",
    "background-color",
    "background-image",
    "background-origin",
    "background-position",
    "background-position-x",
    "background-position-y",
    "background-repeat",
    "background-size",
    "block-size",
    "border",
    "border-block",
    "border-block-color",
    "border-block-end",
    "border-block-end-color",
    "border-block-end-style",
    "border-block-end-width",
    "border-block-start",
    "border-block-start-color",
    "border-block-start-style",
    "border-block-start-width",
    "border-block-style",
    "border-block-width",
    "border-bottom",
    "border-bottom-color",
    "border-bottom-left-radius",
    "border-bottom-right-radius",
    "border-bottom-style",
    "border-bottom-width",
    "border-collapse",
    "border-color",
    "border-end-end-radius",
    "border-end-start-radius",
    "border-image",
    "border-image-outset",
    "border-image-repeat",
    "border-image-slice",
    "border-image-source",
    "border-image-width",
    "border-inline",
    "border-inline-color",
    "border-inline-end",
    "border-inline-end-color",
    "border-inline-end-style",
    "border-inline-end-width",
    "border-inline-start",
    "border-inline-start-color",
    "border-inline-start-style",
    "border-inline-start-width",
    "border-inline-style",
    "border-inline-width",
    "border-left",
    "border-left-color",
    "border-left-style",
    "border-left-width",
    "border-radius",
    "border-right",
    "border-right-color",
    "border-right-style",
    "border-right-width",
    "border-spacing",
    "border-start-end-radius",
    "border-start-start-radius",
    "border-style",
    "border-top",
    "border-top-color",
    "border-top-left-radius",
    "border-top-right-radius",
    "border-top-style",
    "border-top-width",
    "border-width",
    "bottom",
    "box-decoration-break",
    "box-reflect",
    "box-shadow",
    "box-sizing",
    "break-after",
    "break-before",
    "break-inside",
    "caption-side",
    "caret-color",
    "@charset",
    "clear",
    "clip",
    "clip-path",
    "color",
    "color-scheme",
    "column-count",
    "column-fill",
    "column-gap",
    "column-rule",
    "column-rule-color",
    "column-rule-style",
    "column-rule-width",
    "column-span",
    "column-width",
    "columns",
    "content",
    "counter-increment",
    "counter-reset",
    "counter-set",
    "cursor",
    "direction",
    "display",
    "empty-cells",
    "filter",
    "flex",
    "flex-basis",
    "flex-direction",
    "flex-flow",
    "flex-grow",
    "flex-shrink",
    "flex-wrap",
    "float",
    "font",
    "@font-face",
    "font-family",
    "font-feature-settings",
    "@font-feature-values",
    "font-kerning",
    "font-language-override",
    "font-size",
    "font-size-adjust",
    "font-stretch",
    "font-style",
    "font-synthesis",
    "font-variant",
    "font-variant-alternates",
    "font-variant-caps",
    "font-variant-east-asian",
    "font-variant-ligatures",
    "font-variant-numeric",
    "font-variant-position",
    "font-weight",
    "gap",
    "grid",
    "grid-area",
    "grid-auto-columns",
    "grid-auto-flow",
    "grid-auto-rows",
    "grid-column",
    "grid-column-end",
    "grid-column-gap",
    "grid-column-start",
    "grid-gap",
    "grid-row",
    "grid-row-end",
    "grid-row-gap",
    "grid-row-start",
    "grid-template",
    "grid-template-areas",
    "grid-template-columns",
    "grid-template-rows",
    "hanging-punctuation",
    "height",
    "hyphens",
    "hypenate-character",
    "image-rendering",
    "@import",
    "inline-size",
    "inset",
    "inset-block",
    "inset-block-end",
    "inset-block-start",
    "inset-inline",
    "inset-inline-end",
    "inset-inline-start",
    "isolation",
    "justify-content",
    "justify-items",
    "justify-self",
    "@keyframes",
    "left",
    "letter-spacing",
    "line-break",
    "line-height",
    "list-style",
    "list-style-image",
    "list-style-position",
    "list-style-type",
    "margin",
    "margin-block",
    "margin-block-end",
    "margin-block-start",
    "margin-bottom",
    "margin-inline",
    "margin-inline-end",
    "margin-inline-start",
    "margin-left",
    "margin-right",
    "margin-top",
    "mask",
    "mask-clip",
    "mask-composite",
    "mask-image",
    "mask-mode",
    "mask-origin",
    "mask-position",
    "mask-repeat",
    "mask-size",
    "mask-type",
    "max-height",
    "max-width",
    "@media",
    "max-block-size",
    "max-inline-size",
    "min-block-size",
    "min-inline-size",
    "min-height",
    "min-width",
    "mix-blend-mode",
    "object-fit",
    "object-position",
    "offset",
    "offset-anchor",
    "offset-distance",
    "offset-path",
    "offset-rotate",
    "opacity",
    "order",
    "orphans",
    "outline",
    "outline-color",
    "outline-offset",
    "outline-style",
    "outline-width",
    "overflow",
    "overflow-anchor",
    "overflow-wrap",
    "overflow-x",
    "overflow-y",
    "overscroll-behavior",
    "overscroll-behavior-block",
    "overscroll-behavior-inline",
    "overscroll-behavior-x",
    "overscroll-behavior-y",
    "padding",
    "padding-block",
    "padding-block-end",
    "padding-block-start",
    "padding-bottom",
    "padding-inline",
    "padding-inline-end",
    "padding-inline-start",
    "padding-left",
    "padding-right",
    "padding-top",
    "page-break-after",
    "page-break-before",
    "page-break-inside",
    "paint-order",
    "perspective",
    "perspective-origin",
    "place-content",
    "place-items",
    "place-self",
    "pointer-events",
    "position",
    "quotes",
    "resize",
    "right",
    "rotate",
    "row-gap",
    "scale",
    "scroll-behavior",
    "scroll-margin",
    "scroll-margin-block",
    "scroll-margin-block-end",
    "scroll-margin-block-start",
    "scroll-margin-bottom",
    "scroll-margin-inline",
    "scroll-margin-inline-end",
    "scroll-margin-inline-start",
    "scroll-margin-left",
    "scroll-margin-right",
    "scroll-margin-top",
    "scroll-padding",
    "scroll-padding-block",
    "scroll-padding-block-end",
    "scroll-padding-block-start",
    "scroll-padding-bottom",
    "scroll-padding-inline",
    "scroll-padding-inline-end",
    "scroll-padding-inline-start",
    "scroll-padding-left",
    "scroll-padding-right",
    "scroll-padding-top",
    "scroll-snap-align",
    "scroll-snap-stop",
    "scroll-snap-type",
    "scrollbar-color",
    "tab-size",
    "table-layout",
    "text-align",
    "text-align-last",
    "text-combine-upright",
    "text-decoration",
    "text-decoration-color",
    "text-decoration-line",
    "text-decoration-style",
    "text-decoration-thickness",
    "text-emphasis",
    "text-emphasis-color",
    "text-emphasis-position",
    "text-emphasis-style",
    "text-indent",
    "text-justify",
    "text-orientation",
    "text-overflow",
    "text-shadow",
    "text-transform",
    "text-underline-offset",
    "text-underline-position",
    "top",
    "transform",
    "transform-origin",
    "transform-style",
    "transition",
    "transition-delay",
    "transition-duration",
    "transition-property",
    "transition-timing-function",
    "translate",
    "unicode-bidi",
    "user-select",
    "vertical-align",
    "visibility",
    "widows",
    "width",
    "word-break",
    "word-spacing",
    "word-wrap",
    "writing-mode",
    "z-index",
]
